import { describe, expect, test } from "vitest";
import { DEFAULT_ANSWERS, type CompleteInterviewAnswers, type InterviewAnswers } from "./interview.js";
import { renderProject, type PartVersions, type RenderProjectOptions } from "./templates.js";

const VERSIONS: PartVersions = { core: "0.1.0", harness: "0.1.0", whatsapp: "0.1.0", createWappy: "0.1.0" };

function complete(overrides: Partial<InterviewAnswers> = {}): CompleteInterviewAnswers {
  const model = overrides.model ?? DEFAULT_ANSWERS.model;
  return { model };
}

function fileMap(files: { path: string; content: string }[]): Map<string, string> {
  return new Map(files.map((f) => [f.path, f.content]));
}

// Tools/connectors (M9's "tools" step, Shopify) removed entirely: domain connectors are out of
// scope for this open-source repo now — they live in a separate connectors repo/npm scope, wired
// into an agent by hand, not generated by this CLI. The interview is model-only. This file was
// rewritten accordingly (`--allow-test-change`, SPEC.md decisions log).
describe("renderProject — golden path (openai)", () => {
  const opts: RenderProjectOptions = {
    answers: complete({ model: { provider: "openai" } }),
    versions: VERSIONS,
    projectName: "luna-and-co-bot",
  };
  const files = fileMap(renderProject(opts));

  test("renders exactly the §4.1-listed output files — no tools/*.ts, no skills/*.ts", () => {
    expect([...files.keys()].sort()).toEqual(["README.md", "WHATSAPP_SETUP.md", ".env.sample", ".gitignore", "index.ts", "package.json"].sort());
  });

  test("index.ts imports the OpenAI adapter and wires model/memory/sessionProfileStore/router/channel — no tools/skills/rag wiring", () => {
    const indexTs = files.get("index.ts")!;
    expect(indexTs).toContain('import { openai } from "@ai-sdk/openai";');
    expect(indexTs).toContain('openai(process.env.OPENAI_MODEL ?? "gpt-4o")');
    expect(indexTs).toContain("createLibsqlMemory");
    expect(indexTs).toContain("createLibsqlSessionProfileStore");
    expect(indexTs).toContain("sessionProfileStore,");
    expect(indexTs).toContain("createLlmRouter({ model })");
    expect(indexTs).not.toContain("createToolInvoker");
    expect(indexTs).not.toContain("createShopifyToolProvider");
    expect(indexTs).not.toContain("createSkillRegistry");
    expect(indexTs).not.toContain("createKnowledge");
    expect(indexTs).not.toContain("createKnowledgeRag");
    expect(indexTs).toContain("createWhatsAppChannel({");
    expect(indexTs).toContain("export const agent = createAgent({");
  });

  test(".env.sample lists every key needed to run, blank — never a real secret value", () => {
    const env = files.get(".env.sample")!;
    for (const key of ["OPENAI_API_KEY", "WHATSAPP_PHONE_NUMBER_ID", "WHATSAPP_ACCESS_TOKEN", "WHATSAPP_VERIFY_TOKEN", "WHATSAPP_APP_SECRET"]) {
      expect(env).toContain(`\n${key}=\n`);
    }
    // Every non-comment line is a bare "KEY=" placeholder.
    for (const line of env.split("\n").filter((l) => l.trim() !== "" && !l.startsWith("#"))) {
      expect(line).toMatch(/^[A-Z0-9_]+=$/);
    }
  });

  test(".env.sample is grouped, explains where each key comes from, and comments out optional keys", () => {
    const env = files.get(".env.sample")!;
    for (const group of ["Model", "WhatsApp", "Memory"]) expect(env).toContain(`── ${group} `);
    expect(env).toContain("https://platform.openai.com/api-keys");
    expect(env).toContain("\n# MEMORY_DB_URL=\n"); // optional: default applies unless uncommented
    expect(env).not.toContain("\nMEMORY_DB_URL=");
    expect(env).toContain("\n# SESSION_PROFILE_DB_URL=\n"); // M13: on by default, optional to override
    expect(env).not.toContain("SHOPIFY"); // no connector wiring left to need it
  });

  test(".gitignore excludes .env and .wappy/", () => {
    const gi = files.get(".gitignore")!;
    expect(gi).toContain(".env");
    expect(gi).toContain(".wappy/");
  });

  test("package.json is valid JSON, pins @wappy/* part versions, no tools-openapi/libsql-client deps", () => {
    const pkg = JSON.parse(files.get("package.json")!);
    expect(pkg.name).toBe("luna-and-co-bot");
    expect(pkg.type).toBe("module");
    expect(pkg.dependencies["@wappy/core"]).toBe("0.1.0");
    expect(pkg.dependencies["@wappy/harness"]).toBe("0.1.0");
    expect(pkg.dependencies["@wappy/create-agent"]).toBe("0.1.0"); // provides the `wappy` bin `npm run dev` needs
    expect(pkg.dependencies["@ai-sdk/openai"]).toBeDefined();
    expect(pkg.dependencies["@wappy/tools-openapi"]).toBeUndefined();
    expect(pkg.dependencies["@libsql/client"]).toBeUndefined();
  });

  test("README documents every env var, no Tools/Skills line", () => {
    const readme = files.get("README.md")!;
    expect(readme).toContain("OPENAI_API_KEY");
    expect(readme).toContain("cp .env.sample .env");
    expect(readme).toContain("WHATSAPP_APP_SECRET");
    expect(readme).toContain("Memory:** local SQLite");
    expect(readme).toContain("session-profile.db");
    expect(readme).toMatch(/Model:\*\* openai/);
    expect(readme).toContain("wappy dev");
    expect(readme).not.toContain("Skills:**");
    expect(readme).not.toContain("Tools:**");
  });
});

describe("renderProject — model provider branches", () => {
  test.each([
    ["anthropic", "@ai-sdk/anthropic", "anthropic(", "ANTHROPIC_API_KEY"],
    ["gemini", "@ai-sdk/google", "google(", "GOOGLE_GENERATIVE_AI_API_KEY"],
    ["ollama", "ollama-ai-provider", "ollama(", "OLLAMA_BASE_URL"],
  ] as const)("provider=%s imports %s and requires %s", (provider, pkg, ctorPrefix, envVar) => {
    const files = fileMap(renderProject({ answers: complete({ model: { provider } }), versions: VERSIONS }));
    expect(files.get("index.ts")).toContain(`from "${pkg}"`);
    expect(files.get("index.ts")).toContain(ctorPrefix);
    expect(files.get(".env.sample")).toContain(`${envVar}=`);
  });
});

describe("renderProject — WhatsApp credentials are never asked for", () => {
  test("every project lists the four WhatsApp keys, blank, in .env.sample — whatever else was chosen", () => {
    for (const answers of [complete(), complete({ model: { provider: "ollama" } })]) {
      const env = fileMap(renderProject({ answers, versions: VERSIONS })).get(".env.sample")!;
      for (const key of ["WHATSAPP_PHONE_NUMBER_ID", "WHATSAPP_ACCESS_TOKEN", "WHATSAPP_VERIFY_TOKEN", "WHATSAPP_APP_SECRET"]) expect(env).toContain(`\n${key}=\n`);
    }
  });
});

describe("renderProject — no tools, ever", () => {
  test("no tools/*.ts file, no tool-invocation wiring in index.ts, no tools-openapi dependency", () => {
    const files = fileMap(renderProject({ answers: complete(), versions: VERSIONS }));
    expect([...files.keys()].some((p) => p.startsWith("tools/"))).toBe(false);
    expect(files.get("index.ts")).not.toContain("invokeTools");
    expect(JSON.parse(files.get("package.json")!).dependencies["@wappy/tools-openapi"]).toBeUndefined();
  });

  test("no skills/*.ts either — no skill registry wiring in index.ts", () => {
    const files = fileMap(renderProject({ answers: complete(), versions: VERSIONS }));
    expect([...files.keys()].some((p) => p.startsWith("skills/"))).toBe(false);
    expect(files.get("index.ts")).not.toContain("createSkillRegistry");
  });
});

describe("renderProject — incomplete answers refused", () => {
  test("throws if the (only) interview step is still unanswered", () => {
    expect(() => renderProject({ answers: {} as CompleteInterviewAnswers, versions: VERSIONS })).toThrow(/incomplete/);
  });
});
