import type { CompleteInterviewAnswers, ModelProvider } from "./interview.js";
import { assertComplete } from "./interview.js";

/**
 * T9.3 generators (SPEC.md §4.1 output: `index.ts`, `.env.sample`, `.gitignore`, `README.md`,
 * `package.json`) — enum-driven choices (model/framework/memory/router) are rendered by picking
 * between pre-written, already-shipped code paths (a `switch` selecting a one-line adapter
 * constructor), never freshly invented per choice. This module is pure — no I/O, no model calls,
 * fully snapshot-testable (T9.8 builds on this).
 *
 * No tools/connector wiring lives here (removed — see docs/SPEC.md's decisions log): domain
 * connectors (Shopify and anything else) are out of scope for this open-source repo now; they live
 * in a separate connectors repo/npm scope, wired into an agent by hand
 * (`AgentDeps.tools`/`invokeTools`), not generated by this CLI. A "tools" step (M9) and, before it,
 * a "skills" step (M8/M9, removed M12) used to sit here.
 *
 * Memory (local LibSQL file) and the router (LLM) are fixed in v0.1 — the interview no longer offers
 * alternatives that aren't implemented, so there is nothing here that can fail at generation time
 * for lack of code. `.env.sample` is the single place every credential goes; the interview never
 * asks for one.
 */

export interface GeneratedFile {
  path: string;
  content: string;
}

export interface EnvVarSpec {
  name: string;
  required: boolean;
  description: string;
  /** Section heading in `.env.sample`. */
  group: string;
}

/** Version strings for this project's own npm packages, resolved by the caller (e.g. read from
 * each package's own `package.json` at generation time) — kept out of this pure module, which never
 * touches the filesystem. */
export interface PartVersions {
  core: string;
  harness: string;
  whatsapp: string;
  /** `@wappy/create-agent`'s own version — needed as a generated project's OWN dependency (not just
   * a scaffolding tool) so `npm run dev`/`status`/`doctor` can resolve the `wappy` bin it provides. */
  createWappy: string;
}

export interface RenderProjectOptions {
  answers: CompleteInterviewAnswers;
  versions: PartVersions;
  projectName?: string;
}

interface ModelSetup {
  importLine: string;
  constructorExpr: string;
  envVars: EnvVarSpec[];
}

function modelSetup(provider: ModelProvider): ModelSetup {
  switch (provider) {
    case "openai":
      return {
        importLine: 'import { openai } from "@ai-sdk/openai";',
        constructorExpr: 'openai(process.env.OPENAI_MODEL ?? "gpt-4o")',
        envVars: [{ name: "OPENAI_API_KEY", required: true, group: "Model", description: "OpenAI API key — create one at https://platform.openai.com/api-keys" }],
      };
    case "anthropic":
      return {
        importLine: 'import { anthropic } from "@ai-sdk/anthropic";',
        constructorExpr: 'anthropic(process.env.ANTHROPIC_MODEL ?? "claude-sonnet-4-5")',
        envVars: [{ name: "ANTHROPIC_API_KEY", required: true, group: "Model", description: "Anthropic API key — create one at https://console.anthropic.com/settings/keys" }],
      };
    case "gemini":
      return {
        importLine: 'import { google } from "@ai-sdk/google";',
        constructorExpr: 'google(process.env.GEMINI_MODEL ?? "gemini-2.0-flash")',
        envVars: [{ name: "GOOGLE_GENERATIVE_AI_API_KEY", required: true, group: "Model", description: "Google AI Studio API key — create one at https://aistudio.google.com/apikey" }],
      };
    case "ollama":
      return {
        importLine: 'import { ollama } from "ollama-ai-provider";',
        constructorExpr: 'ollama(process.env.OLLAMA_MODEL ?? "llama3.1")',
        envVars: [{ name: "OLLAMA_BASE_URL", required: false, group: "Model", description: "Local Ollama server URL. Default: http://localhost:11434 (no API key needed)." }],
      };
  }
}

/** Conversation memory: a local LibSQL (SQLite) file — the only backend in v0.1. */
const MEMORY_ENV: EnvVarSpec = {
  name: "MEMORY_DB_URL",
  required: false,
  group: "Memory",
  description: "LibSQL URL for conversation memory. Default: a local file at .wappy/memory.db (nothing to set).",
};

/** M13: session profile (facts + current thread state, TTL-bound) — on by default for every
 * generated project, same posture as Memory itself (a local LibSQL file, nothing to configure
 * unless overridden). A separate DB file from MEMORY_DB_URL: a distinct concern (SPEC.md's own
 * "one focused store per concern" call), and it keeps `wappy reset`/inspection simple — one file
 * per store, not a shared schema two different pieces of code both reach into. */
const SESSION_PROFILE_ENV: EnvVarSpec = {
  name: "SESSION_PROFILE_DB_URL",
  required: false,
  group: "Memory",
  description: "LibSQL URL for the session profile (facts + current thread state). Default: a local file at .wappy/session-profile.db (nothing to set).",
};

function renderIndexTs(opts: RenderProjectOptions): string {
  const { answers } = opts;
  const model = modelSetup(answers.model.provider);

  const harnessImports = ["createAgent", "createVercelModel", "createLibsqlMemory", "createLibsqlSessionProfileStore", "createLlmRouter"];

  const lines: string[] = [];
  lines.push('import "dotenv/config";');
  lines.push('import { createInMemoryTracer, systemClock } from "@wappy/core";');
  lines.push(`import { ${[...harnessImports].sort().join(", ")} } from "@wappy/harness";`);
  lines.push('import { createWhatsAppChannel } from "@wappy/whatsapp";');
  lines.push(model.importLine);
  lines.push("");

  lines.push(`const model = createVercelModel({ model: ${model.constructorExpr} });`);
  lines.push('const memory = createLibsqlMemory({ url: process.env.MEMORY_DB_URL ?? "file:.wappy/memory.db" });');
  lines.push('const sessionProfileStore = createLibsqlSessionProfileStore({ url: process.env.SESSION_PROFILE_DB_URL ?? "file:.wappy/session-profile.db" });');
  lines.push("const router = createLlmRouter({ model });");
  lines.push("const tracer = createInMemoryTracer();");
  lines.push("");

  // Exported (not just used locally): `wappy dev` (T9.7) needs channel.receive() to turn a raw
  // webhook into InboundMessages before it can call agent.handle() on each one — the Agent itself
  // only exposes handle(), not receive(), since receiving isn't an agent concern.
  lines.push("export const channel = createWhatsAppChannel({");
  lines.push("  phoneNumberId: process.env.WHATSAPP_PHONE_NUMBER_ID!,");
  lines.push("  accessToken: process.env.WHATSAPP_ACCESS_TOKEN!,");
  lines.push("  clock: systemClock,");
  lines.push("});");
  lines.push("");

  lines.push("// This scaffold ships with no tools wired in. To give the agent tools (a store, a");
  lines.push("// calendar, anything else), see @wappy/core's Tool/ToolProvider interfaces and");
  lines.push("// @wappy/harness's docs on wiring a tool invoker into createAgent below.");
  lines.push("export const agent = createAgent({");
  lines.push("  channel, memory, router, model, tracer,");
  lines.push("  clock: systemClock,");
  lines.push("  sessionProfileStore,");
  lines.push("});");
  lines.push("");

  return lines.join("\n");
}

/** WhatsApp Cloud API credentials — never asked in the interview; always listed in `.env.sample`. */
const WHATSAPP_ENV: EnvVarSpec[] = [
  { name: "WHATSAPP_PHONE_NUMBER_ID", required: true, group: "WhatsApp", description: "Meta developer app > WhatsApp > API Setup > Phone number ID." },
  { name: "WHATSAPP_ACCESS_TOKEN", required: true, group: "WhatsApp", description: "Meta developer app > WhatsApp > API Setup > access token (the temporary one expires in 24h; create a System User token for production)." },
  { name: "WHATSAPP_VERIFY_TOKEN", required: true, group: "WhatsApp", description: "Any string you choose (e.g. a random password). Enter the same value in Meta's webhook config." },
  { name: "WHATSAPP_APP_SECRET", required: true, group: "WhatsApp", description: "Meta developer app > App settings > Basic > App secret. Used to verify webhook signatures, so forged requests are rejected." },
];

/** Every env var the generated project needs, in `.env.sample` order. Exposed for the ledger-driven
 * orchestrator (`generate.ts`), which declares the `.env.sample` step's `SetupManifest.envKeys`
 * from it — one source of truth rather than re-deriving it. */
export function collectEnvVars(opts: RenderProjectOptions): EnvVarSpec[] {
  const { answers } = opts;
  const vars: EnvVarSpec[] = [...modelSetup(answers.model.provider).envVars, ...WHATSAPP_ENV];
  vars.push(MEMORY_ENV);
  vars.push(SESSION_PROFILE_ENV);
  return vars;
}

/** `.env.sample`: copy to `.env` and fill in. Grouped by concern; required keys are left blank,
 * optional ones are commented out so the default applies unless the user opts in. */
function renderEnvSample(opts: RenderProjectOptions): string {
  const vars = collectEnvVars(opts);
  const groups: string[] = [];
  for (const v of vars) if (!groups.includes(v.group)) groups.push(v.group);
  const out: string[] = [
    "# Copy this file to .env and fill in the values. Never commit .env (it is git-ignored).",
    "# Lines starting with # and a KEY are optional: uncomment to override the default.",
    "",
  ];
  for (const g of groups) {
    out.push(`# ── ${g} ${"─".repeat(Math.max(3, 60 - g.length))}`);
    for (const v of vars.filter((x) => x.group === g)) {
      out.push(`# ${v.description}`);
      out.push(v.required ? `${v.name}=` : `# ${v.name}=`);
    }
    out.push("");
  }
  return out.join("\n");
}

function renderGitignore(): string {
  return ["node_modules/", ".env", ".wappy/", "dist/", ""].join("\n");
}

const THIRD_PARTY_VERSIONS: Record<ModelProvider, { pkg: string; range: string }> = {
  openai: { pkg: "@ai-sdk/openai", range: "^2.0.0" },
  anthropic: { pkg: "@ai-sdk/anthropic", range: "^2.0.0" },
  gemini: { pkg: "@ai-sdk/google", range: "^2.0.0" },
  ollama: { pkg: "ollama-ai-provider", range: "^1.2.0" },
};

function renderPackageJson(opts: RenderProjectOptions): string {
  const { answers, versions, projectName } = opts;
  const deps: Record<string, string> = {
    "@wappy/core": versions.core,
    "@wappy/harness": versions.harness,
    "@wappy/whatsapp": versions.whatsapp,
    // Provides the `wappy` bin (dev/status/reset/doctor) that this project's own scripts invoke —
    // a real runtime dependency here, not just the one-time scaffolder.
    "@wappy/create-agent": versions.createWappy,
    ai: "^7.0.0",
    dotenv: "^17.0.0",
  };
  const modelDep = THIRD_PARTY_VERSIONS[answers.model.provider];
  deps[modelDep.pkg] = modelDep.range;
  const pkg = {
    name: projectName ?? "wappy-bot",
    version: "0.1.0",
    private: true,
    type: "module",
    scripts: { dev: "wappy dev", start: "node index.js" },
    dependencies: Object.fromEntries(Object.entries(deps).sort(([a], [b]) => a.localeCompare(b))),
  };
  return `${JSON.stringify(pkg, null, 2)}\n`;
}

/** A dedicated, standalone walkthrough for the one step that isn't a `.env` fill-in: getting a real
 * WhatsApp Cloud API app talking to a webhook that's running on the person's own machine. Kept out
 * of README.md on purpose — the README is meant to be skimmed, this is meant to be followed step by
 * step, and the two don't read well interleaved. `runCli` (cli.ts) points here right after
 * generation finishes, and `wappy dev`'s own missing-token message does too. */
function renderWhatsAppSetup(): string {
  const lines: string[] = [];
  lines.push("# Connecting WhatsApp");
  lines.push("");
  lines.push("This is the one part of setup that isn't just filling in `.env`. It has two halves: getting");
  lines.push("real WhatsApp Cloud API credentials, and giving Meta a URL it can reach even though your agent");
  lines.push("is running on your own machine right now, not a public server.");
  lines.push("");
  lines.push("## 1. Create the Meta app and get your credentials");
  lines.push("");
  lines.push("1. Go to https://developers.facebook.com/apps and create an app (type: Business).");
  lines.push("2. Add the **WhatsApp** product to it.");
  lines.push("3. Under WhatsApp → API Setup, you'll see a test phone number already provided. Copy its");
  lines.push("   **Phone number ID** and the **temporary access token** shown there into `.env` as");
  lines.push("   `WHATSAPP_PHONE_NUMBER_ID` and `WHATSAPP_ACCESS_TOKEN`. (That token expires in 24 hours —");
  lines.push("   fine for trying this out; for anything longer-lived, create a System User token instead,");
  lines.push("   under Business Settings → System Users.)");
  lines.push("4. Under App settings → Basic, copy the **App secret** into `.env` as `WHATSAPP_APP_SECRET`.");
  lines.push("   This is what lets the webhook server verify a request actually came from Meta.");
  lines.push("5. Make up any string yourself (a password you invent, not something Meta gives you) and put");
  lines.push("   it in `.env` as `WHATSAPP_VERIFY_TOKEN`. You'll enter this exact same string into Meta's");
  lines.push("   webhook config in step 3 below — it's just a shared secret the two sides agree on.");
  lines.push("");
  lines.push("## 2. Get a public URL for your local machine");
  lines.push("");
  lines.push("Meta needs to send webhook requests to a real, public URL. Your machine doesn't have one by");
  lines.push("default, so `npm run dev` (which runs `wappy dev`) opens a tunnel for you automatically and");
  lines.push("prints a public URL that forwards to your local server. You don't need to install or");
  lines.push("configure anything extra for this — it's already wired in.");
  lines.push("");
  lines.push("```sh");
  lines.push("npm run dev");
  lines.push("# ...");
  lines.push("# Webhook server listening on http://localhost:3000/webhook");
  lines.push("# Public webhook URL: https://some-random-name.loca.lt/webhook");
  lines.push("```");
  lines.push("");
  lines.push("Keep that command running while you're testing. If you'd rather use your own tunnel (ngrok,");
  lines.push("Cloudflare Tunnel, etc.) instead of the built-in one, run `npm run dev -- --no-tunnel` and point");
  lines.push("your own tunnel at `http://localhost:3000/webhook` — either way, what Meta needs in the next");
  lines.push("step is whatever public URL ends in `/webhook`.");
  lines.push("");
  lines.push("## 3. Point Meta's webhook at that URL");
  lines.push("");
  lines.push("1. In the Meta app, go to WhatsApp → Configuration.");
  lines.push("2. Under Webhook, click Edit and paste in the public URL from step 2 (the one ending in");
  lines.push("   `/webhook`), plus the same `WHATSAPP_VERIFY_TOKEN` string you put in `.env`.");
  lines.push("3. Click Verify and save — Meta calls your webhook once to confirm it's really up, and your");
  lines.push("   server (already running from step 2) answers that check automatically.");
  lines.push("4. Under \"Webhook fields,\" subscribe to **messages**. Without this, Meta never actually");
  lines.push("   forwards incoming messages to your webhook, even once verification succeeds.");
  lines.push("");
  lines.push("## 4. Test it");
  lines.push("");
  lines.push("Send a WhatsApp message to the test number shown on the API Setup page. It should reach your");
  lines.push("running `npm run dev` process and get a real reply back.");
  lines.push("");
  lines.push("If nothing happens: check the terminal running `npm run dev` for errors first, then re-check");
  lines.push("that the webhook shows as verified and subscribed to `messages` in Meta's UI. `wappy doctor`");
  lines.push("(once available) checks your `.env` and connectivity for you.");
  lines.push("");
  lines.push("A new tunnel URL from the built-in tunnel changes every time you restart `npm run dev` — if");
  lines.push("you stop and restart it, you'll need to paste the new URL back into Meta's webhook config.");
  lines.push("");
  return lines.join("\n");
}

function renderReadme(opts: RenderProjectOptions): string {
  const { answers } = opts;
  const vars = collectEnvVars(opts);
  const lines: string[] = [];
  lines.push(`# ${opts.projectName ?? "wappy-bot"}`);
  lines.push("");
  lines.push("A WhatsApp agent generated by `npm create @wappy/agent`.");
  lines.push("");
  lines.push("## 1. Add your credentials");
  lines.push("");
  lines.push("```sh");
  lines.push("cp .env.sample .env   # then fill in every key that has no default");
  lines.push("```");
  lines.push("");
  lines.push("`.env` is git-ignored — secrets never leave your machine. Where to get each key:");
  lines.push("");
  for (const v of vars) lines.push(`- \`${v.name}\`${v.required ? "" : " (optional)"} — ${v.description}`);
  lines.push("");
  lines.push("## 2. Connect WhatsApp");
  lines.push("");
  lines.push("See [`WHATSAPP_SETUP.md`](./WHATSAPP_SETUP.md) for the full walkthrough: creating the Meta app,");
  lines.push("getting a public webhook URL from your own machine, and wiring it into Meta's webhook config.");
  lines.push("");
  lines.push("## 3. What was generated");
  lines.push("");
  lines.push(`- **Model:** ${answers.model.provider}`);
  lines.push("- **Memory:** local SQLite file (`.wappy/memory.db`), plus a session profile (`.wappy/session-profile.db`) — facts and where the conversation currently stands, TTL-bound");
  lines.push("");
  lines.push("No tools/connectors are wired by default — see `index.ts`'s comment above `createAgent` for how to add one.");
  lines.push("");
  lines.push("Once WHATSAPP_SETUP.md's steps are done, `npm run dev` (this project's `wappy dev`) starts the");
  lines.push("webhook server. Run `wappy status` any time to see what's done vs. pending, and `wappy doctor` to");
  lines.push("validate your env + connectivity.");
  lines.push("");
  return lines.join("\n");
}


/**
 * Renders every project file for a completed interview (§4.1's output list). Throws
 * `NotYetImplementedError` for any enum choice not yet backed by real code (see file header) —
 * callers (the CLI, in practice) should surface that as a clear install-time failure, not attempt
 * to generate broken code. Pure: no filesystem access, no model calls — see `generate.ts` (a later
 * T9.3 step) for the ledger-driven orchestrator that actually writes these to disk.
 */
export function renderProject(opts: RenderProjectOptions): GeneratedFile[] {
  assertComplete(opts.answers);
  return [
    { path: "index.ts", content: renderIndexTs(opts) },
    { path: ".env.sample", content: renderEnvSample(opts) },
    { path: ".gitignore", content: renderGitignore() },
    { path: "package.json", content: renderPackageJson(opts) },
    { path: "README.md", content: renderReadme(opts) },
    { path: "WHATSAPP_SETUP.md", content: renderWhatsAppSetup() },
  ];
}
