import type { CompleteInterviewAnswers, ModelProvider } from "./interview.js";
import { assertComplete } from "./interview.js";

/**
 * T9.3 generators (SPEC.md §4.1 output: `index.ts`, `.env.sample`, `.gitignore`, `README.md`,
 * `package.json`) — enum-driven choices (model/framework/memory/router) are rendered by picking
 * between pre-written, already-shipped code paths (a `switch` selecting a one-line adapter
 * constructor), never freshly invented per choice. This module is pure — no I/O, no model calls,
 * fully snapshot-testable (T9.8 builds on this).
 *
 * No tools/connector wiring lives here (removed — see docs/SPEC.md's decisions log): domain
 * connectors (Shopify and anything else) are out of scope for this open-source repo now; they live
 * in a separate connectors repo/npm scope, wired into an agent by hand
 * (`AgentDeps.tools`/`invokeTools`), not generated by this CLI. A "tools" step (M9) and, before it,
 * a "skills" step (M8/M9, removed M12) used to sit here.
 *
 * Raw conversation history (local LibSQL file) and the router (LLM) are fixed — the interview no
 * longer offers alternatives that aren't implemented, so there is nothing here that can fail at
 * generation time for lack of code. Retrieved knowledge/RAG (a separate concern) IS a real choice —
 * see the `memory` interview step and `KNOWLEDGE_ENV`/`COGNEE_ENV` below. `.env.sample` is the
 * single place every credential goes; the interview never asks for one.
 */

export interface GeneratedFile {
  path: string;
  content: string;
}

export interface EnvVarSpec {
  name: string;
  required: boolean;
  description: string;
  /** Section heading in `.env.sample`. */
  group: string;
}

/** Version strings for this project's own npm packages, resolved by the caller (e.g. read from
 * each package's own `package.json` at generation time) — kept out of this pure module, which never
 * touches the filesystem. */
export interface PartVersions {
  core: string;
  harness: string;
  whatsapp: string;
  /** Only actually depended on when the productivity-agent interview step is answered "yes" — see
   * `renderPackageJson`. Always resolved regardless, same as every other part, so there's one code
   * path for reading real installed versions, not a productivity-specific branch in `versions.ts`. */
  productivity: string;
  /** Same "only when productivity=yes" story as `productivity` above. */
  connectorGoogle: string;
  /** Only actually depended on when `memory.backend === "cognee"` — same "always resolved
   * regardless" story as `productivity`/`connectorGoogle` above. */
  connectorCognee: string;
  /** `@wappy_ai/create-agent`'s own version — needed as a generated project's OWN dependency (not just
   * a scaffolding tool) so `npm run dev`/`status`/`doctor` can resolve the `wappy` bin it provides. */
  createWappy: string;
}

export interface RenderProjectOptions {
  answers: CompleteInterviewAnswers;
  versions: PartVersions;
  projectName?: string;
}

interface ModelSetup {
  importLine: string;
  constructorExpr: string;
  envVars: EnvVarSpec[];
}

function modelSetup(provider: ModelProvider): ModelSetup {
  switch (provider) {
    case "openai":
      return {
        importLine: 'import { openai } from "@ai-sdk/openai";',
        constructorExpr: 'openai(process.env.OPENAI_MODEL ?? "gpt-4o")',
        envVars: [{ name: "OPENAI_API_KEY", required: true, group: "Model", description: "OpenAI API key — create one at https://platform.openai.com/api-keys" }],
      };
    case "anthropic":
      return {
        importLine: 'import { anthropic } from "@ai-sdk/anthropic";',
        constructorExpr: 'anthropic(process.env.ANTHROPIC_MODEL ?? "claude-sonnet-4-5")',
        envVars: [{ name: "ANTHROPIC_API_KEY", required: true, group: "Model", description: "Anthropic API key — create one at https://console.anthropic.com/settings/keys" }],
      };
    case "gemini":
      return {
        importLine: 'import { google } from "@ai-sdk/google";',
        constructorExpr: 'google(process.env.GEMINI_MODEL ?? "gemini-2.0-flash")',
        envVars: [{ name: "GOOGLE_GENERATIVE_AI_API_KEY", required: true, group: "Model", description: "Google AI Studio API key — create one at https://aistudio.google.com/apikey" }],
      };
    case "ollama":
      return {
        importLine: 'import { ollama } from "ollama-ai-provider";',
        constructorExpr: 'ollama(process.env.OLLAMA_MODEL ?? "llama3.1")',
        envVars: [{ name: "OLLAMA_BASE_URL", required: false, group: "Model", description: "Local Ollama server URL. Default: http://localhost:11434 (no API key needed)." }],
      };
  }
}

/** Conversation memory: a local LibSQL (SQLite) file — the only backend in v0.1. */
const MEMORY_ENV: EnvVarSpec = {
  name: "MEMORY_DB_URL",
  required: false,
  group: "Memory",
  description: "LibSQL URL for conversation memory. Default: a local file at .wappy/memory.db (nothing to set).",
};

/** M13: session profile (facts + current thread state, TTL-bound) — on by default for every
 * generated project, same posture as Memory itself (a local LibSQL file, nothing to configure
 * unless overridden). A separate DB file from MEMORY_DB_URL: a distinct concern (SPEC.md's own
 * "one focused store per concern" call), and it keeps `wappy reset`/inspection simple — one file
 * per store, not a shared schema two different pieces of code both reach into. */
const SESSION_PROFILE_ENV: EnvVarSpec = {
  name: "SESSION_PROFILE_DB_URL",
  required: false,
  group: "Memory",
  description: "LibSQL URL for the session profile (facts + current thread state). Default: a local file at .wappy/session-profile.db (nothing to set).",
};

function renderIndexTs(opts: RenderProjectOptions): string {
  const { answers } = opts;
  const model = modelSetup(answers.model.provider);
  const productivity = answers.productivity.enabled;
  const memoryBackend = answers.memory.backend;

  const harnessImports = ["createAgent", "createVercelModel", "createLibsqlMemory", "createLibsqlSessionProfileStore", "createLlmRouter", "createKnowledge", "createKnowledgeRag"];
  const whatsappImports = ["createWhatsAppChannel"];

  const lines: string[] = [];
  lines.push('import "dotenv/config";');
  lines.push('import { createInMemoryTracer, systemClock } from "@wappy_ai/core";');
  lines.push(`import { ${[...harnessImports].sort().join(", ")} } from "@wappy_ai/harness";`);
  lines.push(`import { ${[...whatsappImports].sort().join(", ")} } from "@wappy_ai/whatsapp";`);
  if (memoryBackend === "local") {
    lines.push('import { createClient } from "@libsql/client";');
  } else {
    lines.push('import { createCogneeKnowledge } from "@wappy_ai/connector-cognee";');
  }
  if (productivity) {
    lines.push('import { createConnectUiServer, createGoogleAssistant } from "@wappy_ai/productivity";');
    lines.push('import { createCalendarSearchFn, createGmailSearchFn, createGoogleOAuthPlugin, createGoogleTokenStore } from "@wappy_ai/connector-google";');
  }
  lines.push(model.importLine);
  lines.push("");

  lines.push(`const model = createVercelModel({ model: ${model.constructorExpr} });`);
  lines.push('const memory = createLibsqlMemory({ url: process.env.MEMORY_DB_URL ?? "file:.wappy/memory.db" });');
  lines.push('const sessionProfileStore = createLibsqlSessionProfileStore({ url: process.env.SESSION_PROFILE_DB_URL ?? "file:.wappy/session-profile.db" });');
  lines.push("const router = createLlmRouter({ model });");
  lines.push("const tracer = createInMemoryTracer();");
  lines.push("");

  // Retrieved knowledge/RAG — unconditional (independent of the productivity agent): the local
  // backend (BM25-by-default, already shipped in @wappy_ai/harness) costs nothing extra, so there's
  // no reason to gate it behind anything. `memory.backend` only picks which Knowledge implementation
  // backs it.
  if (memoryBackend === "cognee") {
    lines.push("// Bring-your-own Cognee instance (self-hosted or cloud) — see COGNEE_SETUP.md.");
    lines.push('const knowledge = createCogneeKnowledge({ baseUrl: process.env.COGNEE_BASE_URL!, apiKey: process.env.COGNEE_API_KEY });');
  } else {
    lines.push('const knowledgeClient = createClient({ url: process.env.KNOWLEDGE_DB_URL ?? "file:.wappy/knowledge.db" });');
    lines.push("const knowledge = createKnowledge({ client: knowledgeClient });");
  }
  lines.push("const retrieveRag = createKnowledgeRag({ knowledge, memory });");
  lines.push("");

  // Exported (not just used locally): `wappy dev` (T9.7) needs channel.receive() to turn a raw
  // webhook into InboundMessages before it can call agent.handle() on each one — the Agent itself
  // only exposes handle(), not receive(), since receiving isn't an agent concern. No WhatsApp
  // Message Template is ever configured here — every reply this project sends (the reactive agent's
  // own, or a matched task's, below) is a direct response to an inbound message, so it's always
  // inside the 24h session window Meta opens when the contact messages you; that rule only bites a
  // message that pushes on its own, unprompted, which this project deliberately never does.
  lines.push("export const channel = createWhatsAppChannel({");
  lines.push("  phoneNumberId: process.env.WHATSAPP_PHONE_NUMBER_ID!,");
  lines.push("  accessToken: process.env.WHATSAPP_ACCESS_TOKEN!,");
  lines.push("  clock: systemClock,");
  lines.push("});");
  lines.push("");

  lines.push("// This scaffold ships with no tools wired in. To give the agent tools (a store, a");
  lines.push("// calendar, anything else), see @wappy_ai/core's Tool/ToolProvider interfaces and");
  lines.push("// @wappy_ai/harness's docs on wiring a tool invoker into createAgent below.");
  lines.push(`export const ${productivity ? "reactiveAgent" : "agent"} = createAgent({`);
  lines.push("  channel, memory, router, model, tracer,");
  lines.push("  clock: systemClock,");
  lines.push("  sessionProfileStore,");
  lines.push("  retrieveRag,");
  lines.push("});");
  lines.push("");

  if (productivity) {
    lines.push("// Productivity agent: reads (never writes) the user's own Gmail/Calendar, for ANY question");
    lines.push("// phrased in normal language — no saved tasks, no fixed list of things it can answer. See");
    lines.push('// GOOGLE_SETUP.md for the one-time Google connection; without it, a matched question just');
    lines.push('// replies honestly that it needs "Connect Google" tapped first on the local connect page.');
    lines.push("const googleConfig = {");
    lines.push('  clientId: process.env.GOOGLE_CLIENT_ID ?? "",');
    lines.push('  clientSecret: process.env.GOOGLE_CLIENT_SECRET ?? "",');
    lines.push('  redirectUri: process.env.GOOGLE_REDIRECT_URI ?? "http://localhost:3001/google/callback",');
    lines.push("};");
    lines.push('const googleTokenStore = createGoogleTokenStore({ url: process.env.GOOGLE_TOKENS_DB_URL ?? "file:.wappy/google-tokens.db" });');
    lines.push("const googlePlugin = createGoogleOAuthPlugin({ config: googleConfig, tokenStore: googleTokenStore, clock: systemClock });");
    lines.push("");
    lines.push("const googleAssistant = createGoogleAssistant({");
    lines.push("  model, clock: systemClock,");
    lines.push("  connectors: {");
    lines.push("    gmail: createGmailSearchFn({ config: googleConfig, tokenStore: googleTokenStore, clock: systemClock }),");
    lines.push("    calendar: createCalendarSearchFn({ config: googleConfig, tokenStore: googleTokenStore, clock: systemClock }),");
    lines.push("  },");
    lines.push("});");
    lines.push("");
    lines.push("// Wraps the reactive agent: every inbound message is offered real Gmail/Calendar search tools");
    lines.push("// first (the model itself decides whether the message actually needs them, and constructs its");
    lines.push("// own query/date-range — @wappy_ai/harness's createVercelModel already runs the full");
    lines.push("// multi-step tool-calling loop internally); anything that didn't touch either tool falls");
    lines.push("// through to the normal reactive agent unchanged.");
    lines.push("export const agent = {");
    lines.push("  async handle(message: Parameters<typeof reactiveAgent.handle>[0]) {");
    lines.push("    const routed = await googleAssistant.maybeHandle(message);");
    lines.push("    if (routed.handled) return channel.send(message.contactId, { text: routed.reply! });");
    lines.push("    return reactiveAgent.handle(message);");
    lines.push("  },");
    lines.push("};");
    lines.push("");
    lines.push("export const taskUiServer = createConnectUiServer({ oauthConnect: googlePlugin });");
    lines.push("");
  }

  return lines.join("\n");
}

/** WhatsApp Cloud API credentials — never asked in the interview; always listed in `.env.sample`. */
const WHATSAPP_ENV: EnvVarSpec[] = [
  { name: "WHATSAPP_PHONE_NUMBER_ID", required: true, group: "WhatsApp", description: "Meta developer app > WhatsApp > API Setup > Phone number ID." },
  { name: "WHATSAPP_ACCESS_TOKEN", required: true, group: "WhatsApp", description: "Meta developer app > WhatsApp > API Setup > access token (the temporary one expires in 24h; create a System User token for production)." },
  { name: "WHATSAPP_VERIFY_TOKEN", required: true, group: "WhatsApp", description: "Any string you choose (e.g. a random password). Enter the same value in Meta's webhook config." },
  { name: "WHATSAPP_APP_SECRET", required: true, group: "WhatsApp", description: "Meta developer app > App settings > Basic > App secret. Used to verify webhook signatures, so forged requests are rejected." },
];

/** Both optional/blank — a project works fully without them (a Gmail/Calendar question just replies
 * honestly that it needs "Connect Google" tapped first). See GOOGLE_SETUP.md for how to get real
 * values. */
const GOOGLE_ENV: EnvVarSpec[] = [
  { name: "GOOGLE_CLIENT_ID", required: false, group: "Google", description: "Your own Google Cloud OAuth Client ID — see GOOGLE_SETUP.md." },
  { name: "GOOGLE_CLIENT_SECRET", required: false, group: "Google", description: "Your own Google Cloud OAuth Client secret — see GOOGLE_SETUP.md." },
];

/** Only meaningful when `memory.backend === "local"` (the default) — listed unconditionally anyway,
 * same "always list the local-file default" precedent as `MEMORY_ENV`/`SESSION_PROFILE_ENV`. */
const KNOWLEDGE_ENV: EnvVarSpec = {
  name: "KNOWLEDGE_DB_URL",
  required: false,
  group: "Memory",
  description: "LibSQL URL for local knowledge/RAG storage (only used when the memory backend is local). Default: a local file at .wappy/knowledge.db (nothing to set).",
};

/** Only pushed when `memory.backend === "cognee"` — see COGNEE_SETUP.md for how to get real values. */
const COGNEE_ENV: EnvVarSpec[] = [
  { name: "COGNEE_BASE_URL", required: true, group: "Memory", description: "Your Cognee instance's base URL — self-hosted (e.g. http://localhost:8000) or Cognee Cloud. See COGNEE_SETUP.md." },
  { name: "COGNEE_API_KEY", required: false, group: "Memory", description: "Only needed for Cognee Cloud or an auth-enabled self-hosted instance. See COGNEE_SETUP.md." },
];

/** Every env var the generated project needs, in `.env.sample` order. Exposed for the ledger-driven
 * orchestrator (`generate.ts`), which declares the `.env.sample` step's `SetupManifest.envKeys`
 * from it — one source of truth rather than re-deriving it. */
export function collectEnvVars(opts: RenderProjectOptions): EnvVarSpec[] {
  const { answers } = opts;
  const vars: EnvVarSpec[] = [...modelSetup(answers.model.provider).envVars, ...WHATSAPP_ENV];
  vars.push(MEMORY_ENV);
  vars.push(SESSION_PROFILE_ENV);
  vars.push(KNOWLEDGE_ENV);
  if (answers.memory.backend === "cognee") {
    vars.push(...COGNEE_ENV);
  }
  if (answers.productivity.enabled) {
    vars.push(...GOOGLE_ENV);
  }
  return vars;
}

/** `.env.sample`: copy to `.env` and fill in. Grouped by concern; required keys are left blank,
 * optional ones are commented out so the default applies unless the user opts in. */
function renderEnvSample(opts: RenderProjectOptions): string {
  const vars = collectEnvVars(opts);
  const groups: string[] = [];
  for (const v of vars) if (!groups.includes(v.group)) groups.push(v.group);
  const out: string[] = [
    "# Copy this file to .env and fill in the values. Never commit .env (it is git-ignored).",
    "# Lines starting with # and a KEY are optional: uncomment to override the default.",
    "",
  ];
  for (const g of groups) {
    out.push(`# ── ${g} ${"─".repeat(Math.max(3, 60 - g.length))}`);
    for (const v of vars.filter((x) => x.group === g)) {
      out.push(`# ${v.description}`);
      out.push(v.required ? `${v.name}=` : `# ${v.name}=`);
    }
    out.push("");
  }
  return out.join("\n");
}

function renderGitignore(): string {
  return ["node_modules/", ".env", ".wappy/", "dist/", ""].join("\n");
}

const THIRD_PARTY_VERSIONS: Record<ModelProvider, { pkg: string; range: string }> = {
  openai: { pkg: "@ai-sdk/openai", range: "^2.0.0" },
  anthropic: { pkg: "@ai-sdk/anthropic", range: "^2.0.0" },
  gemini: { pkg: "@ai-sdk/google", range: "^2.0.0" },
  ollama: { pkg: "ollama-ai-provider", range: "^1.2.0" },
};

function renderPackageJson(opts: RenderProjectOptions): string {
  const { answers, versions, projectName } = opts;
  const deps: Record<string, string> = {
    "@wappy_ai/core": versions.core,
    "@wappy_ai/harness": versions.harness,
    "@wappy_ai/whatsapp": versions.whatsapp,
    // Provides the `wappy` bin (dev/status/reset/doctor) that this project's own scripts invoke —
    // a real runtime dependency here, not just the one-time scaffolder.
    "@wappy_ai/create-agent": versions.createWappy,
    ai: "^7.0.0",
    dotenv: "^17.0.0",
  };
  const modelDep = THIRD_PARTY_VERSIONS[answers.model.provider];
  deps[modelDep.pkg] = modelDep.range;
  if (answers.memory.backend === "local") {
    // createKnowledge({ client }) takes a real @libsql/client Client, not a URL — index.ts builds
    // one directly, so it needs to be a direct dependency here, not just a transitive one.
    deps["@libsql/client"] = "0.18.0";
  } else {
    deps["@wappy_ai/connector-cognee"] = versions.connectorCognee;
  }
  if (answers.productivity.enabled) {
    deps["@wappy_ai/productivity"] = versions.productivity;
    deps["@wappy_ai/connector-google"] = versions.connectorGoogle;
  }
  const pkg = {
    name: projectName ?? "wappy-bot",
    version: "0.1.0",
    private: true,
    type: "module",
    // The `ai` package (Vercel AI SDK — createVercelModel's real dependency, pulled in by every
    // generated project) requires Node >=22, not the commonly-assumed >=20 — confirmed against its
    // own package.json, not guessed. Declared here so `npm install` actually warns on an
    // incompatible Node version instead of failing confusingly later at runtime.
    engines: { node: ">=22" },
    // No build step exists yet — index.ts is run directly via wappy dev's dynamic import (dev.ts),
    // never compiled to index.js. `start: "node index.js"` was a stale placeholder that fails
    // MODULE_NOT_FOUND on any real install (caught by hand-testing a real npm install through a
    // local registry, not by the unit tests, which never actually run `npm start`). `start` now
    // means the same thing `dev` does until a real production build step exists.
    scripts: { dev: "wappy dev", start: "wappy dev" },
    dependencies: Object.fromEntries(Object.entries(deps).sort(([a], [b]) => a.localeCompare(b))),
  };
  return `${JSON.stringify(pkg, null, 2)}\n`;
}

/** A dedicated, standalone walkthrough for the one step that isn't a `.env` fill-in: getting a real
 * WhatsApp Cloud API app talking to a webhook that's running on the person's own machine. Kept out
 * of README.md on purpose — the README is meant to be skimmed, this is meant to be followed step by
 * step, and the two don't read well interleaved. `runCli` (cli.ts) points here right after
 * generation finishes, and `wappy dev`'s own missing-token message does too. */
function renderWhatsAppSetup(opts: RenderProjectOptions): string {
  const lines: string[] = [];
  lines.push("# Connecting WhatsApp");
  lines.push("");
  lines.push("This is the one part of setup that isn't just filling in `.env`. It has two halves: getting");
  lines.push("real WhatsApp Cloud API credentials, and giving Meta a URL it can reach even though your agent");
  lines.push("is running on your own machine right now, not a public server.");
  lines.push("");
  lines.push("## 1. Create the Meta app and get your credentials");
  lines.push("");
  lines.push("1. Go to https://developers.facebook.com/apps and create an app (type: Business).");
  lines.push("2. Add the **WhatsApp** product to it.");
  lines.push("3. Under WhatsApp → API Setup, you'll see a test phone number already provided. Copy its");
  lines.push("   **Phone number ID** and the **temporary access token** shown there into `.env` as");
  lines.push("   `WHATSAPP_PHONE_NUMBER_ID` and `WHATSAPP_ACCESS_TOKEN`. (That token expires in 24 hours —");
  lines.push("   fine for trying this out; for anything longer-lived, create a System User token instead,");
  lines.push("   under Business Settings → System Users.)");
  lines.push("4. Under App settings → Basic, copy the **App secret** into `.env` as `WHATSAPP_APP_SECRET`.");
  lines.push("   This is what lets the webhook server verify a request actually came from Meta.");
  lines.push("5. Make up any string yourself (a password you invent, not something Meta gives you) and put");
  lines.push("   it in `.env` as `WHATSAPP_VERIFY_TOKEN`. You'll enter this exact same string into Meta's");
  lines.push("   webhook config in step 3 below — it's just a shared secret the two sides agree on.");
  lines.push("");
  lines.push("## 2. Get a public URL for your local machine");
  lines.push("");
  lines.push("Meta needs to send webhook requests to a real, public URL. Your machine doesn't have one by");
  lines.push("default, so `npm run dev` (which runs `wappy dev`) opens a tunnel for you automatically and");
  lines.push("prints a public URL that forwards to your local server. You don't need to install or");
  lines.push("configure anything extra for this — it's already wired in.");
  lines.push("");
  lines.push("```sh");
  lines.push("npm run dev");
  lines.push("# ...");
  lines.push("# Webhook server listening on http://localhost:3000/webhook");
  lines.push("# Public webhook URL: https://some-random-name.loca.lt/webhook");
  lines.push("```");
  lines.push("");
  lines.push("Keep that command running while you're testing. If you'd rather use your own tunnel (ngrok,");
  lines.push("Cloudflare Tunnel, etc.) instead of the built-in one, run `npm run dev -- --no-tunnel` and point");
  lines.push("your own tunnel at `http://localhost:3000/webhook` — either way, what Meta needs in the next");
  lines.push("step is whatever public URL ends in `/webhook`.");
  lines.push("");
  lines.push("## 3. Point Meta's webhook at that URL");
  lines.push("");
  lines.push("1. In the Meta app, go to WhatsApp → Configuration.");
  lines.push("2. Under Webhook, click Edit and paste in the public URL from step 2 (the one ending in");
  lines.push("   `/webhook`), plus the same `WHATSAPP_VERIFY_TOKEN` string you put in `.env`.");
  lines.push("3. Click Verify and save — Meta calls your webhook once to confirm it's really up, and your");
  lines.push("   server (already running from step 2) answers that check automatically.");
  lines.push("4. Under \"Webhook fields,\" subscribe to **messages**. Without this, Meta never actually");
  lines.push("   forwards incoming messages to your webhook, even once verification succeeds.");
  lines.push("");
  lines.push("## 4. Test it");
  lines.push("");
  lines.push("Send a WhatsApp message to the test number shown on the API Setup page. It should reach your");
  lines.push("running `npm run dev` process and get a real reply back.");
  lines.push("");
  lines.push("If nothing happens: check the terminal running `npm run dev` for errors first, then re-check");
  lines.push("that the webhook shows as verified and subscribed to `messages` in Meta's UI. `wappy doctor`");
  lines.push("(once available) checks your `.env` and connectivity for you.");
  lines.push("");
  lines.push("A new tunnel URL from the built-in tunnel changes every time you restart `npm run dev` — if");
  lines.push("you stop and restart it, you'll need to paste the new URL back into Meta's webhook config.");
  lines.push("");

  if (opts.answers.productivity.enabled) {
    lines.push("## 5. About the productivity agent and WhatsApp Message Templates");
    lines.push("");
    lines.push("You do **not** need to set up a WhatsApp Message Template for anything in this project. A");
    lines.push("Message Template is Meta's requirement for a message your agent sends unprompted, outside the");
    lines.push("24 hours since the contact last messaged you — this project deliberately never does that.");
    lines.push("Every reply, including a matched productivity task's, is a direct response to something the");
    lines.push("contact just said, so it's always inside that open window. See GOOGLE_SETUP.md for connecting");
    lines.push("Gmail/Calendar, which is the only extra setup the productivity agent needs.");
    lines.push("");
  }

  return lines.join("\n");
}

/** Generated only when the productivity-agent interview step is "yes". Bring-your-own Google OAuth
 * client — same unavoidable-one-time-setup category as WHATSAPP_SETUP.md, mirroring its format.
 * Unlike WhatsApp, actually CONNECTING is a click on the connect page, not a step in this file — see
 * that page's own "Connect Google" card. */
function renderGoogleSetup(): string {
  const lines: string[] = [];
  lines.push("# Connecting Google (Calendar + Gmail)");
  lines.push("");
  lines.push("The productivity agent needs this — real read access to your own Calendar and Gmail, full");
  lines.push("read (never write, never a shared Wappy-operated account). Without it, a Gmail/Calendar");
  lines.push('question just replies honestly that it needs "Connect Google" tapped first, instead of');
  lines.push("failing silently.");
  lines.push("");
  lines.push("## 1. Create your own Google Cloud OAuth client");
  lines.push("");
  lines.push("This can't be skipped or automated — Google requires every app to be registered under");
  lines.push("someone's own Cloud project, same category of one-time setup as WHATSAPP_SETUP.md.");
  lines.push("");
  lines.push("1. Go to https://console.cloud.google.com and create a project (or use an existing one).");
  lines.push("2. Go to APIs & Services → Library, enable **Google Calendar API** and **Gmail API**.");
  lines.push("3. Go to APIs & Services → OAuth consent screen. Choose **External**, fill in the required");
  lines.push("   fields, and leave Publishing status as **Testing** — this is a personal tool, not a");
  lines.push("   public app, so Google's full app-review process doesn't apply (Testing mode supports up");
  lines.push("   to 100 users, which is every user this project has).");
  lines.push("4. Go to APIs & Services → Credentials → Create Credentials → OAuth client ID.");
  lines.push("5. Application type: **Web application**.");
  lines.push("6. Under Authorized redirect URIs, add exactly: `http://localhost:3001/google/callback`");
  lines.push("   (this must match `index.ts`'s `GOOGLE_REDIRECT_URI` default exactly — only change both");
  lines.push("   together if you've customized `CONNECT_UI_PORT`).");
  lines.push("7. Copy the **Client ID** and **Client secret** into `.env` as `GOOGLE_CLIENT_ID` and");
  lines.push("   `GOOGLE_CLIENT_SECRET`.");
  lines.push("");
  lines.push("## 2. Connect — one click, on the local connect page");
  lines.push("");
  lines.push("Restart `npm run dev` after filling in `.env`. Open the connect page URL it prints — you'll");
  lines.push("see a **Connect Google** card. Tap it, sign in with your own Google account, approve the real");
  lines.push("consent screen (it will look unverified, since this is your own personal app in Testing");
  lines.push("mode — that's expected, not an error). You'll land back on the page showing");
  lines.push("**✓ Google connected**.");
  lines.push("");
  lines.push("No CLI command, no second install — that's the whole flow.");
  lines.push("");
  lines.push("## 3. Test it");
  lines.push("");
  lines.push('Just text your bot something like "what\'s on my calendar today" or "find emails about the');
  lines.push('flight" — no task to create first, any real question about your Gmail/Calendar works. You');
  lines.push("should get a real reply, not the earlier \"Gmail/Calendar isn't connected yet\" reply.");
  lines.push("");
  return lines.join("\n");
}

/** Generated only when `memory.backend === "cognee"`. Bring-your-own Cognee instance — same
 * unavoidable-one-time-setup category as GOOGLE_SETUP.md, mirroring its format. Unlike Google,
 * there's no in-app "connect" click here — Cognee is reached directly over HTTP via `COGNEE_BASE_URL`,
 * no OAuth handshake. */
function renderCogneeSetup(): string {
  const lines: string[] = [];
  lines.push("# Connecting Cognee (knowledge-graph memory)");
  lines.push("");
  lines.push("Retrieved knowledge (anything ingested via `@wappy_ai/harness`'s Knowledge/RAG) is backed by");
  lines.push("Cognee instead of the local default — a self-hosted or cloud service that builds a knowledge");
  lines.push("graph of entities/relationships rather than literal keyword matching, and is designed to keep");
  lines.push("correcting itself over repeated ingests. Never a shared Wappy-operated instance — you bring");
  lines.push("your own, same pattern as everything else here.");
  lines.push("");
  lines.push("## 1. Get a Cognee instance running");
  lines.push("");
  lines.push("Three real paths, confirmed by actually running each of these (not just read from docs):");
  lines.push("");
  lines.push("- **Self-hosted, Docker (easiest)**: a single copy-pasteable compose file, no cloning —");
  lines.push("  https://github.com/topoteretes/cognee/blob/main/docs/minimal-docker-compose.md. Starts");
  lines.push("  the real REST API on `http://localhost:8000`.");
  lines.push("- **Self-hosted, no Docker**: `pip install cognee` (needs Python 3.10–3.14), then");
  lines.push("  `uvicorn cognee.api.client:app --host 0.0.0.0 --port 8011`. Its default graph backend");
  lines.push("  (Ladybug/Kuzu) needs a native shared library that isn't on PyPI — grab the prebuilt one for");
  lines.push("  your platform from https://github.com/LadybugDB/ladybug/releases and point");
  lines.push("  `LBUG_C_API_LIB_PATH` at it, or just use the Docker path above, which doesn't have this step.");
  lines.push("- **Cloud**: sign up for Cognee Cloud, create a project, and get a base URL + API key from");
  lines.push("  their dashboard: https://www.cognee.ai/");
  lines.push("");
  lines.push("**Confirmed by real testing, not a guess**: you do NOT need an LLM provider API key to get");
  lines.push("started. With no `LLM_API_KEY` set on the Cognee server, it falls back to free local models —");
  lines.push("`fastembed` for embeddings, `GLiNER` for entity extraction — and a real ingest → cognify →");
  lines.push("search round trip works end to end on that alone. Setting a real LLM key gets you higher-");
  lines.push("quality entity/relationship extraction; it's an upgrade, not a requirement.");
  lines.push("");
  lines.push("## 2. Get a token (self-hosted) or none at all");
  lines.push("");
  lines.push("Self-hosted Cognee can run two ways — pick whichever matches your instance:");
  lines.push("");
  lines.push("- **No auth (simplest for local use)**: set `ENABLE_BACKEND_ACCESS_CONTROL=false` on the");
  lines.push("  Cognee server and leave `COGNEE_API_KEY` blank below. Nothing else to do.");
  lines.push("- **Auth enabled (the default if you don't set that)**: register a user, log in, then create");
  lines.push("  an API key — three real calls against your own instance:");
  lines.push("  ```sh");
  lines.push("  # 1. register");
  lines.push('  curl -X POST $COGNEE_BASE_URL/api/v1/auth/register -H "Content-Type: application/json" \\');
  lines.push('    -d \'{"email":"you@example.com","password":"choose-a-password"}\'');
  lines.push("  # 2. log in -> access_token");
  lines.push('  curl -X POST $COGNEE_BASE_URL/api/v1/auth/login -H "Content-Type: application/x-www-form-urlencoded" \\');
  lines.push('    -d "username=you@example.com&password=choose-a-password"');
  lines.push("  # 3. create an API key with that access_token -> this is your COGNEE_API_KEY");
  lines.push('  curl -X POST $COGNEE_BASE_URL/api/v1/auth/api-keys -H "Authorization: Bearer <access_token>" \\');
  lines.push('    -H "Content-Type: application/json" -d \'{"name":"wappy"}\'');
  lines.push("  ```");
  lines.push("- **Cognee Cloud**: skip all of the above — your API key comes straight from their dashboard.");
  lines.push("");
  lines.push("## 3. Fill in `.env`");
  lines.push("");
  lines.push("- `COGNEE_BASE_URL` — your instance's URL (e.g. `http://localhost:8000` for self-hosted, or");
  lines.push("  the URL Cognee Cloud gives you).");
  lines.push("- `COGNEE_API_KEY` — the key from step 2 (Cognee Cloud or an auth-enabled self-hosted");
  lines.push("  instance), or leave blank for a no-auth self-hosted instance.");
  lines.push("");
  lines.push("## 4. Test it");
  lines.push("");
  lines.push("This scaffold wires Cognee into the agent's RAG lookup (`retrieveRag`, used automatically on");
  lines.push("any message the router decides needs it) — but doesn't yet call `knowledge.ingest()` from");
  lines.push("anywhere on its own, since there's no built-in \"ingest this\" command or trigger in this");
  lines.push("scaffold. Said honestly, not invented: to actually put something into Cognee to recall later,");
  lines.push("call `knowledge.ingest(sourceId, text)` yourself — e.g. from a small script, or by wiring a");
  lines.push("tool/command that calls it — using the `knowledge` instance `index.ts` already constructs.");
  lines.push("");
  return lines.join("\n");
}

function renderReadme(opts: RenderProjectOptions): string {
  const { answers } = opts;
  const vars = collectEnvVars(opts);
  const lines: string[] = [];
  lines.push(`# ${opts.projectName ?? "wappy-bot"}`);
  lines.push("");
  lines.push("A WhatsApp agent generated by `npm create @wappy_ai/agent`.");
  lines.push("");
  lines.push("## 1. Add your credentials");
  lines.push("");
  lines.push("```sh");
  lines.push("cp .env.sample .env   # then fill in every key that has no default");
  lines.push("```");
  lines.push("");
  lines.push("`.env` is git-ignored — secrets never leave your machine. Where to get each key:");
  lines.push("");
  for (const v of vars) lines.push(`- \`${v.name}\`${v.required ? "" : " (optional)"} — ${v.description}`);
  lines.push("");
  lines.push("## 2. Connect WhatsApp");
  lines.push("");
  lines.push("See [`WHATSAPP_SETUP.md`](./WHATSAPP_SETUP.md) for the full walkthrough: creating the Meta app,");
  lines.push("getting a public webhook URL from your own machine, and wiring it into Meta's webhook config.");
  lines.push("");
  lines.push("## 3. What was generated");
  lines.push("");
  lines.push(`- **Model:** ${answers.model.provider}`);
  lines.push("- **Memory:** local SQLite file (`.wappy/memory.db`), plus a session profile (`.wappy/session-profile.db`) — facts and where the conversation currently stands, TTL-bound");
  lines.push(
    answers.memory.backend === "cognee"
      ? "- **Memory backend:** Cognee — retrieved knowledge (anything you ingest) is backed by a Cognee instance you provide (self-hosted or cloud), building a knowledge graph of entities/relationships rather than keyword matching. See [`COGNEE_SETUP.md`](./COGNEE_SETUP.md)."
      : "- **Memory backend:** Local (LibSQL) — retrieved knowledge is stored and searched entirely on your own machine (BM25 keyword matching), no account or extra setup needed.",
  );
  if (answers.productivity.enabled) {
    lines.push("- **Productivity agent:** on — reads (never writes) your own Gmail/Calendar for any question phrased in normal language, no saved tasks and no fixed list of things it can answer, no cron and no WhatsApp Message Template ever needed. Replies honestly that it's not connected until you connect Google (see [`GOOGLE_SETUP.md`](./GOOGLE_SETUP.md), then tap \"Connect Google\" on the local connect page).");
  }
  lines.push("");
  lines.push("No tools/connectors are wired by default — see `index.ts`'s comment above `createAgent` for how to add one.");
  lines.push("");
  lines.push("Once WHATSAPP_SETUP.md's steps are done, `npm run dev` (this project's `wappy dev`) starts the");
  lines.push(
    answers.productivity.enabled
      ? "webhook server and the local Google-connect page (its URL prints alongside the webhook URL)."
      : "webhook server.",
  );
  lines.push("Run `wappy status` any time to see what's done vs. pending, and `wappy doctor` to");
  lines.push("validate your env + connectivity.");
  lines.push("");
  return lines.join("\n");
}


/**
 * Renders every project file for a completed interview (§4.1's output list). Throws
 * `NotYetImplementedError` for any enum choice not yet backed by real code (see file header) —
 * callers (the CLI, in practice) should surface that as a clear install-time failure, not attempt
 * to generate broken code. Pure: no filesystem access, no model calls — see `generate.ts` (a later
 * T9.3 step) for the ledger-driven orchestrator that actually writes these to disk.
 */
export function renderProject(opts: RenderProjectOptions): GeneratedFile[] {
  assertComplete(opts.answers);
  const files: GeneratedFile[] = [
    { path: "index.ts", content: renderIndexTs(opts) },
    { path: ".env.sample", content: renderEnvSample(opts) },
    { path: ".gitignore", content: renderGitignore() },
    { path: "package.json", content: renderPackageJson(opts) },
    { path: "README.md", content: renderReadme(opts) },
    { path: "WHATSAPP_SETUP.md", content: renderWhatsAppSetup(opts) },
  ];
  if (opts.answers.productivity.enabled) files.push({ path: "GOOGLE_SETUP.md", content: renderGoogleSetup() });
  if (opts.answers.memory.backend === "cognee") files.push({ path: "COGNEE_SETUP.md", content: renderCogneeSetup() });
  return files;
}
