import { describe, expect, test } from "vitest";
import { selectTools } from "@wappy/harness";
import { createOpenApiToolProvider, generateHugeSpec } from "@wappy/tools-openapi";

// T7.10's own "Tests introduced" list: "800-tool set → selector returns ≤K, includes the obviously
// relevant tool for 20 labeled queries" — this is the cross-package half of that requirement: proves
// harness's M6 BM25 tool-selector (packages/harness/src/tool-selector.ts) actually works end-to-end
// against a REAL ToolProvider generated by tools-openapi's engine, not just a hand-rolled fixture.
describe("harness's selectTools finds the right tool among ~800 generated from a real OpenAPI spec", () => {
  test("a message about order shipping status selects getOrderStatus, not unrelated filler tools", async () => {
    const spec = generateHugeSpec(800);
    const { provider } = await createOpenApiToolProvider({
      name: "huge",
      source: spec as unknown as Record<string, unknown>,
      envPrefix: "HUGE_",
      ssrf: { allowPrivateNetworks: true },
    });
    const tools = await provider.listTools();
    expect(tools.length).toBeGreaterThan(700);

    const selected = selectTools({ tools, message: "what's the shipping status of my order?", maxTokens: 500 });
    expect(selected.some((t) => t.name === "getOrderStatus")).toBe(true);
    expect(selected.length).toBeLessThan(tools.length); // genuinely narrowed down, not just everything
  });

  test("a message about searching for products selects searchProductCatalog", async () => {
    const spec = generateHugeSpec(800);
    const { provider } = await createOpenApiToolProvider({
      name: "huge",
      source: spec as unknown as Record<string, unknown>,
      envPrefix: "HUGE_",
      ssrf: { allowPrivateNetworks: true },
    });
    const tools = await provider.listTools();

    const selected = selectTools({ tools, message: "search the product catalog for running shoes", maxTokens: 500 });
    expect(selected.some((t) => t.name === "searchProductCatalog")).toBe(true);
  });

  test("a message about loyalty points selects getCustomerLoyaltyBalance", async () => {
    const spec = generateHugeSpec(800);
    const { provider } = await createOpenApiToolProvider({
      name: "huge",
      source: spec as unknown as Record<string, unknown>,
      envPrefix: "HUGE_",
      ssrf: { allowPrivateNetworks: true },
    });
    const tools = await provider.listTools();

    const selected = selectTools({ tools, message: "how many loyalty points does this customer have?", maxTokens: 500 });
    expect(selected.some((t) => t.name === "getCustomerLoyaltyBalance")).toBe(true);
  });
});
